include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - file_names: true
    - prefer_single_quotes: true
    - sort_constructors_first: true
    - directives_ordering: true
    - public_member_api_docs: false

analyzer:
  errors:
    invalid_annotation_target: ignore
