#!/bin/bash

if [ ! -f util/.serverpod_util_root ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/run_tests_web_build"
    exit 1
fi

set -e

echo "### Web build compatibility test"
echo "### Validates that serverpod_database can be used in Flutter web apps."

cd tests/serverpod_web_build_test

echo "### Running flutter build web..."
flutter build web

echo "### Running web build test..."
flutter test

echo "### Web build compatibility test passed!"
