#!/bin/bash

if [ ! -f util/.serverpod_util_root ]; then
    echo "Run this script from the root of the Serverpod repository"
    echo "I.e. util/run_tests_analyze"
    exit 1
fi

# Source the package lists from all_packages
source util/all_packages

LOG_LEVEL="--fatal-infos"
for arg in "$@"
do
    # Check if the argument is the --allow-infos flag
    # If it is, set the log level to --fatal-warnings instead of --fatal-infos
    if [ "$arg" == "--allow-infos" ] ; then
        LOG_LEVEL="--fatal-warnings"
        break
    elif [ "$arg" == "--allow-warnings" ] ; then
        LOG_LEVEL="--no-fatal-warnings"
        break
    fi
done

declare -a projectPaths=(
    "${FLUTTER_PACKAGES_PATHS[@]}"
    "${DART_PACKAGES_PATHS[@]}"
)

exit_code=0

echo "### Running dart analyze with log level '$LOG_LEVEL'"
for i in "${projectPaths[@]}"
do
   dart analyze $LOG_LEVEL $i

   if [ $? != 0 ]; then
     exit_code=1
   fi
done

exit $exit_code
